FROM oven/bun AS base
WORKDIR /app

FROM base AS install
WORKDIR /app

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile

FROM node:22-alpine AS build
WORKDIR /app

COPY --from=install /app/node_modules ./node_modules
COPY . .

RUN npm run build

ENV NODE_ENV=production

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "start" ]