export const ADMIN_LEADER_REFRESH_ERROR = "401_ADMIN_LEADER_REFRESH_ERROR";

export const JWT_MISSING_ERROR = "401_JWT_MISSING_ERROR";

export const PLAYER_JWT_RENEW_ERROR = "401_PLAYER_JWT_RENEW_ERROR";

export const UNAUTHORIZED_ERROR = "401_UNAUTHORIZED_ERROR";

export const COULD_NOT_RENEW_JWT = "401_COULD_NOT_RENEW_JWT";
